#!/bin/sh

PID_FILE="/var/run/mjpg_streamer.pid"

case "$1" in
  start)
    V4L_DEVICE=$(v4l2-ctl --list-devices|grep -A1 usb|sed 's/^[[:space:]]*//g'|grep '^/dev' | head -1)
    if [ "x$V4L_DEVICE" = "x" ]; then
      echo "WARNING: No webcams found!"
      exit 1
    fi

    export LD_LIBRARY_PATH=/usr/data/mjpg-streamer/lib/:/usr/data/mjpg-streamer/lib/mjpg-streamer/
    start-stop-daemon -S -b -m -p $PID_FILE --exec "/usr/data/mjpg-streamer/bin/mjpg_streamer" -- -i "/usr/data/mjpg-streamer/lib/mjpg-streamer/input_uvc.so -r 1280x720 -d $V4L_DEVICE -f 10 -n -timeout 15" -o "/usr/data/mjpg-streamer/lib/mjpg-streamer/output_http.so -p 8080"
    ;;
  stop)
    start-stop-daemon -K -p $PID_FILE > /dev/null 2>&1
    ;;

  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage:"
    echo "    $0 {start|stop|restart}"
    exit 1
esac

exit $?

